// client/src/components/organisms/provider/theme-provider.tsx
'use client'

import { useThemeStore } from '$modules/theme/store'
import { Theme } from '$modules/theme/types'
import { useEffect } from 'react'

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  const { theme } = useThemeStore()

  useEffect(() => {
    const root = document.documentElement
    
    if (theme === Theme.DARK) {
      root.setAttribute('data-theme', 'dark')
    } else {
      root.removeAttribute('data-theme')
    }
  }, [theme])

  return <>{children}</>
}

// vue-client/src/components/organisms/theme-provider.vue
<script setup lang="ts">
import { watch, onMounted } from 'vue'
import { useThemeStore, Theme } from '@/stores/theme'

const themeStore = useThemeStore()

function updateTheme() {
  const root = document.documentElement

  if (themeStore.theme === Theme.DARK) {
    root.setAttribute('data-theme', 'dark')
  } else {
    root.removeAttribute('data-theme')
  }
}

onMounted(() => {
  updateTheme()
})

watch(
  () => themeStore.theme,
  () => {
    updateTheme()
  },
)
</script>

<template>
  <slot />
</template>
