// client/src/components/organisms/theme-toggler.tsx
import { Button } from '$components/ui/button'
import { useThemeStore } from '$modules/theme/store'
import { Theme } from '$modules/theme/types'
import { MoonIcon, SunIcon } from 'lucide-react'

export const ThemeToggler = () => {
  const { theme, toggleTheme } = useThemeStore()
  return (
    <Button variant="ghost" onClick={toggleTheme}>
      {theme === Theme.DARK ? (
        <SunIcon className="size-4" />
      ) : (
        <MoonIcon className="size-4" />
      )}
    </Button>
  )
}

// vue-client/src/components/organisms/navbar/theme-toggler.vue
<script setup lang="ts">
import { Theme, useTheme } from '@/modules/theme/composables/use-theme'
import { Button } from '@/components/ui/button'
import { SunIcon, MoonIcon } from 'lucide-vue-next'

const { toggleTheme, theme } = useTheme()
</script>

<template>
  <Button variant="ghost" @click="toggleTheme">
    <SunIcon v-if="theme === Theme.LIGHT" />
    <MoonIcon v-else />
  </Button>
</template>
